version: "3"

services:
  apprest:
    image: openjdk:11-slim
    ports:
      - 9966:9966
    volumes:
      - ../spring-petclinic-rest:/app
      - ./log:/var/log/demo
    working_dir: /app
    command: ./mvnw spring-boot:run
    networks:
      - demo_default
  appangular:
    build:
      context: .
      dockerfile: Dockerfile_angular
    ports:
      - 4200:4200
    volumes:
      - ../spring-petclinic-angular:/app
    working_dir: /app
    command: bash -c "npm link && ng serve --host=0.0.0.0"
    networks:
      - demo_default
networks:
  demo_default:
    external: true
